### ISSUE TITLE
Node 10 invalid stored block lengths

### ISSUE THREAD

**Issue by ForsakenHarmony** [isaacs/minizlib#4]
Not sure if this is an error in node, might be

```
ZlibError: zlib: invalid stored block lengths
  at Zlib.(anonymous function).onerror (node_modules/minizlib/index.js:131:21)
  at Unzip.write (node_modules/minizlib/index.js:255:31)
```

**Comment by addaleax** [comment]
Can you give more information on how to trigger this/Whether this is specific to Node.js 10?

Are you using this module directly or through a dependent module (e.g. npm)?

**Comment by ForsakenHarmony** [comment]
sorry, seem to actually have been a problem with dependencies from previous node versions

**Comment by ForsakenHarmony** [comment]
ok it still happens, but it's not deterministic

**Comment by ForsakenHarmony** [comment]
https://github.com/developit/preact-cli/tree/next-hrmny

run `yarn` -> `yarn test`
